(define (problem my-problem-6)
	(:domain my-pddl-domain)
	(:objects object0 object1 object2 object3 object4 object5 object6 object7 object8)

(:init
    (predicate0)
    (predicate6 object0)
    (predicate6 object1)
    (predicate6 object2)
    (predicate6 object3)
    (predicate6 object4)
    (predicate6 object5)
    (predicate6 object6)
    (predicate6 object7)
    (predicate6 object8)
    (predicate1 object8 object6)
    (predicate1 object8 object2)
    (predicate1 object8 object1)
    (predicate1 object8 object4)
    (predicate1 object8 object5)
    (predicate1 object8 object3)
    (predicate1 object8 object0)
    (predicate1 object8 object7)
    (predicate1 object6 object2)
    (predicate1 object6 object1)
    (predicate1 object6 object4)
    (predicate1 object6 object5)
    (predicate1 object6 object3)
    (predicate1 object6 object0)
    (predicate1 object6 object7)
    (predicate1 object2 object1)
    (predicate1 object2 object4)
    (predicate1 object2 object5)
    (predicate1 object2 object3)
    (predicate1 object2 object0)
    (predicate1 object2 object7)
    (predicate1 object1 object4)
    (predicate1 object1 object5)
    (predicate1 object1 object3)
    (predicate1 object1 object0)
    (predicate1 object1 object7)
    (predicate1 object4 object5)
    (predicate1 object4 object3)
    (predicate1 object4 object0)
    (predicate1 object4 object7)
    (predicate1 object5 object3)
    (predicate1 object5 object0)
    (predicate1 object5 object7)
    (predicate1 object3 object0)
    (predicate1 object3 object7)
    (predicate1 object0 object7)
)

(:goal (and (predicate4 object0) (predicate4 object1) (predicate4 object2) (predicate4 object3) (predicate4 object4) (predicate4 object5) (predicate4 object6) (predicate4 object7) (predicate4 object8)))
)
